#!/bin/bash

echo "Use source!"
echo "You have to use unique IDs for project. In GCP any project id that has ever been used cannot be used again! Use GCP_DEPL_VERSION to define new unique id."

export GCP_ADMIN_VERSION=<GIVE-YOUR-UNIQUE-NUMBER>
export GCP_INFRA_VERSION=<GIVE-YOUR-UNIQUE-NUMBER>

export TF_VAR_ADMIN_PROJ_ID=<GIVE-ADMIN-PROJECT-ID>-id-$GCP_ADMIN_VERSION
export TF_VAR_ADMIN_PROJ_NAME=<GIVE-ADMIN-PROJECT-NAME>
export TF_VAR_TERRA_BACKEND_BUCKET_NAME=<GIVE-BUCKET-NAME>-$GCP_ADMIN_VERSION
export TF_VAR_INFRA_PROJ_ID=<GIVE-INFRA-PROJECT-ID>-id-$GCP_INFRA_VERSION
export TF_VAR_INFRA_PROJ_NAME=<GIVE-INFRA-PROJECT-NAME>
export TF_VAR_FOLDER_ID=<GIVE-FOLDER-ID>
export TF_VAR_ORG_ID=<GIVE-ORGANIZATION-ID>
export TF_VAR_BILLING_ACCOUNT_ID=<GIVE-BILLING-ACCOUNT-ID>
export TF_VAR_CONFIG_NAME=<GIVE-CONFIG-NAME>
export TF_VAR_REGION=<GIVE-REGION>
export TF_VAR_ZONE=<GIVE-ZONE>
export TF_VAR_ACCOUNT=<GIVE-ACCOUNT>

echo "TF_VAR_ADMIN_PROJ_ID: $TF_VAR_ADMIN_PROJ_ID"
echo "TF_VAR_ADMIN_PROJ_NAME: $TF_VAR_ADMIN_PROJ_NAME"
echo "TF_VAR_TERRA_BACKEND_BUCKET_NAME: $TF_VAR_TERRA_BACKEND_BUCKET_NAME"
echo "TF_VAR_INFRA_PROJ_ID: $TF_VAR_INFRA_PROJ_ID"
echo "TF_VAR_INFRA_PROJ_NAME: $TF_VAR_INFRA_PROJ_NAME"
echo "TF_VAR_CONFIG_NAME: $TF_VAR_CONFIG_NAME"
# Do not list these in demos:
#echo "TF_VAR_FOLDER_ID: $TF_VAR_FOLDER_ID"
#echo "TF_VAR_ORG_ID: $TF_VAR_ORG_ID"
#echo "TF_VAR_BILLING_ACCOUNT_ID: $TF_VAR_BILLING_ACCOUNT_ID"

#echo "List configurations:"
#gcloud config configurations list

